import { describe, expect, it } from "vitest";
import { createGovernedArtifact, GovernedArtifactEnvelope } from "../src/artifact.js";
import { ADMITTED_CASTELLAN_PROFILE } from "../src/castellan-doctrine-profile.js";
import { CastellanMissionFormation, CastellanOperatingLayer, PredicateDetermination, RectorPredicateInterpretationContract } from "../src/castellan-mission-formation.js";
import { ADMITTED_RECTOR } from "../src/rector-officer-profile.js";
import { CastellanInquiry, CastellanTurnDisposition, SecretariatMissionIntake } from "../src/secretariat-mission-dossier.js";
const context = { identityFactory: (p: string) => p + "-castellan-test", now: () => "2026-08-03T07:00:00.000Z" }; const intake = new SecretariatMissionIntake(), castellan = new CastellanMissionFormation(), layer = new CastellanOperatingLayer();
function open() { return intake.open({ authenticatedOperatorRef: "operator@1", rawIntent: "Build mission" }, "castellan-turn", context); }
function answered(disposition: PredicateDetermination["disposition"] = "RESOLVED") { const d = open(), result = castellan.evaluate(d, undefined, undefined, context); if (result.artifactType !== "CastellanInquiry") throw new Error(); const q = result as GovernedArtifactEnvelope<CastellanInquiry>; const p = intake.presentInquiry(d, q), a = intake.recordAnswers(p, [{ questionId: q.payload.question.questionId, rawAnswer: "Outcome" }]), h = intake.prepareCastellanHandoff(a, context); const i = createGovernedArtifact<RectorPredicateInterpretationContract>("RectorPredicateInterpretation", "Rector", a.correlationId, { officerPersonaRef: ADMITTED_RECTOR.identity + "@2", dossierRef: a.identity + "@3", handoffRef: h.identity + "@1", determinations: [{ questionId: q.payload.question.questionId, predicate: q.payload.question.predicate, disposition, values: disposition === "RESOLVED" ? ["Outcome"] : [], rationale: "Exact turn assessment." }], researchPerformed: false, judgmentRendered: false, authorityCreated: false }, { coreDoctrineRef: "coredoctrine-core-v1@6", lexiconRef: "imperiumlexicon-core-v1@4", officeProfileRef: ADMITTED_CASTELLAN_PROFILE.identity + "@2", vocabularyUses: [{ termId: "LEX-012", value: "castellan", lexiconRef: "imperiumlexicon-core-v1@4" }] }, [ADMITTED_RECTOR.identity + "@2", a.identity + "@3", h.identity + "@1"], context); return { d: a, h, assessment: layer.recordAssessment(a, h, i, context), q }; }
describe("Castellan one-question formation", () => {
  it("issues one question only", () => { const result = castellan.evaluate(open(), undefined, undefined, context); expect(result.artifactType).toBe("CastellanInquiry"); const q = result as GovernedArtifactEnvelope<CastellanInquiry>; expect(q.payload.question.predicate).toBe("purpose"); });
  it("accepts one resolved response and advances only by disposition", () => { const x = answered(); const result = castellan.evaluate(x.d, x.h, x.assessment, context); expect(result).toMatchObject({ artifactType: "CastellanTurnDisposition", payload: { action: "ACCEPT_AND_ADVANCE", acceptedDetermination: { predicate: "purpose" } } }); });
  it.each(["AMBIGUOUS", "CONTRADICTORY", "UNUSABLE"] as const)("does not accept %s", (state) => { const x = answered(state); const result = castellan.evaluate(x.d, x.h, x.assessment, context) as GovernedArtifactEnvelope<CastellanTurnDisposition>; expect(result.artifactType).toBe("CastellanTurnDisposition"); expect(result.payload.action).not.toBe("ACCEPT_AND_ADVANCE"); });
  it("requires exactly one Rector determination", () => { const x = answered(); const forged = { ...x.assessment, payload: { ...x.assessment.payload, determination: { ...x.assessment.payload.determination, questionId: "other" } } }; expect(() => castellan.evaluate(x.d, x.h, forged, context)).toThrow("exact active answered question"); });
  it("keeps prohibited powers absent", () => { expect(Object.getOwnPropertyNames(CastellanMissionFormation.prototype)).toEqual(["constructor", "evaluate"]); });
});
