import { describe, expect, it } from "vitest";
import { createGovernedArtifact, GovernedArtifactEnvelope } from "../src/artifact.js";
import { CastellanMissionFormation } from "../src/castellan-mission-formation.js";
import { ADMITTED_ISOLDE } from "../src/isolde-officer-profile.js";
import { ADMITTED_CASTELLAN_PROFILE } from "../src/castellan-doctrine-profile.js";
import { IsoldeSecretariatOfficer } from "../src/isolde-secretariat-officer.js";
import { ADMITTED_ISOLDE_AGENT } from "../src/isolde-agent-definition.js";
import { CastellanInquiry, CastellanTurnDisposition } from "../src/secretariat-mission-dossier.js";

const context = { identityFactory: (p: string) => p + "-isolde-test", now: () => "2026-08-03T07:00:00.000Z" };
const officer = new IsoldeSecretariatOfficer(); const castellan = new CastellanMissionFormation();
function open() { return officer.openMission("operator@1", "Build the mission with me.", "isolde-turn", context); }
function inquiry(dossier = open()) { const value = castellan.evaluate(dossier, undefined, undefined, context); if (value.artifactType !== "CastellanInquiry") throw new Error("expected inquiry"); return value as GovernedArtifactEnvelope<CastellanInquiry>; }
function disposition(dossier: ReturnType<typeof open>, action: CastellanTurnDisposition["action"], message: string) { return createGovernedArtifact<CastellanTurnDisposition>("CastellanTurnDisposition", "Castellan", dossier.correlationId, { dossierRef: dossier.identity + "@" + dossier.version, questionId: dossier.payload.presentedQuestions.at(-1)!.questionId, action, operatorFacingMessage: message, authorityCreated: false }, { coreDoctrineRef: "coredoctrine-core-v1@6", lexiconRef: "imperiumlexicon-core-v1@4", officeProfileRef: ADMITTED_CASTELLAN_PROFILE.identity + "@2", vocabularyUses: [{ termId: "LEX-012", value: "castellan", lexiconRef: "imperiumlexicon-core-v1@4" }] }, [dossier.identity + "@" + dossier.version], context); }

describe("Isolde single-question transport", () => {
  it("opens a dossier without interpreting Operator intent", () => { const dossier = open(); expect(dossier.payload).toMatchObject({ rawIntent: "Build the mission with me.", officerPersonaRef: ADMITTED_ISOLDE.identity + "@2", residentAgentDefinitionRef: ADMITTED_ISOLDE_AGENT.identity + "@2", acceptedDeterminations: [] }); expect(dossier.sourceRefs).toContain(ADMITTED_ISOLDE_AGENT.identity + "@2"); expect(JSON.stringify(dossier.payload)).not.toContain("interpretation"); });
  it("presents exactly one Castellan question without rewriting it", () => { const dossier = open(), q = inquiry(dossier); const result = officer.presentQuestion(dossier, q, context); expect(q.payload.question.predicate).toBe("purpose"); expect(result.presentation.payload.exactQuestion).toBe(q.payload.question.exactQuestion); expect(result.dossier.payload.presentedQuestions).toHaveLength(1); });
  it("records and immediately hands off one exact raw response", () => { const dossier = open(), q = inquiry(dossier), presented = officer.presentQuestion(dossier, q, context).dossier; const result = officer.recordResponse(presented, "  My exact answer.  ", context); expect(result.receipt.payload.rawResponse).toBe("  My exact answer.  "); expect(result.dossier.payload.answers).toEqual([{ questionId: q.payload.question.questionId, rawAnswer: "  My exact answer.  ", responseReceiptRef: result.receipt.identity + "@1" }]); expect(result.handoff.payload.dossierRef).toBe(result.dossier.identity + "@3"); });
  it("relays Castellan requery wording exactly and never advances locally", () => { const initial = open(), q = inquiry(initial), presented = officer.presentQuestion(initial, q, context).dossier, answered = officer.recordResponse(presented, "Bananas", context).dossier; const d = disposition(answered, "REQUERY_SAME_QUESTION", "That is not what I asked."); const result = officer.relayDisposition(answered, d, context); expect(result.relay.payload.exactMessage).toBe("That is not what I asked."); expect(result.dossier.payload.acceptedDeterminations).toEqual([]); expect(result.dossier.payload.state).toBe("AWAITING_CASTELLAN_INQUIRY"); });
  it("refuses batch responses, stale dossiers, and altered dispositions", () => { const initial = open(), q = inquiry(initial), presented = officer.presentQuestion(initial, q, context).dossier; expect(() => officer.recordResponse({ ...presented, status: "SUPERSEDED" }, "answer", context)).toThrow("exact current"); const answered = officer.recordResponse(presented, "answer", context).dossier; const d = disposition(answered, "REQUERY_SAME_QUESTION", "That is not what I asked."); expect(() => officer.relayDisposition(answered, { ...d, payload: { ...d.payload, dossierRef: "other@1" } }, context)).toThrow("exact matching Castellan"); });
  it("exposes transport operations only", () => { expect(Object.getOwnPropertyNames(IsoldeSecretariatOfficer.prototype).sort()).toEqual(["constructor", "openMission", "presentQuestion", "recordResponse", "relayDisposition"].sort()); });
});
