import { describe, expect, it } from "vitest";
import { PredicateDetermination } from "../src/castellan-mission-formation.js";
import { GovernedArtifactEnvelope } from "../src/artifact.js";
import { ADMITTED_RECTOR } from "../src/rector-resident-officer-contract.js";
import { ADMITTED_RECTOR_AGENT } from "../src/rector-agent-definition.js";
import { RectorCastellanOfficer, RectorCognitivePort } from "../src/rector-castellan-officer.js";
import { IsoldeSecretariatOfficer } from "../src/isolde-secretariat-officer.js";
import { CastellanInquiry, CastellanTurnDisposition } from "../src/secretariat-mission-dossier.js";
const context = { identityFactory: (p: string) => p + "-rector-turn", now: () => "2026-08-03T07:00:00.000Z" };
class Cognition implements RectorCognitivePort { disposition: PredicateDetermination["disposition"] = "RESOLVED"; assessMissionPredicates(d: Parameters<RectorCognitivePort["assessMissionPredicates"]>[0], sourceAnswerRef: string) { const q = d.presentedQuestions.at(-1)!; return { determinations: [{ questionId: q.questionId, predicate: q.predicate, disposition: this.disposition, values: this.disposition === "RESOLVED" ? ["Outcome"] : [], rationale: "Exact response assessment.", sourceAnswerRef, evidence: [{ exactExcerpt: "Outcome", derivation: "QUOTED" as const, value: this.disposition === "RESOLVED" ? "Outcome" : undefined, rationale: "Exact Operator wording." }] }] }; } }
function turn(cognition = new Cognition()) { const isolde = new IsoldeSecretariatOfficer(), rector = new RectorCastellanOfficer(cognition), d = isolde.openMission("operator@1", "Build mission", "rector", context), result = rector.initiateInquiry(d, context); if (result.artifactType !== "CastellanInquiry") throw new Error(); const q = result as GovernedArtifactEnvelope<CastellanInquiry>; const p = isolde.presentQuestion(d, q, context).dossier, response = isolde.recordResponse(p, "Outcome", context); return { isolde, rector, d: response.dossier, h: response.handoff }; }
describe("Rector one-turn evaluation", () => {
  it("remains the exact admitted Castellan Officer", () => { expect(ADMITTED_RECTOR.payload).toMatchObject({ officerId: "rector", officeId: "Castellan", state: "ADMITTED" }); });
  it("evaluates one response under the exact resident Agent and returns Castellan disposition", () => { const x = turn(), result = x.rector.evaluateHandoff(x.d, x.h, context); expect(result.interpretation.payload).toMatchObject({ residentAgentDefinitionRef: `${ADMITTED_RECTOR_AGENT.identity}@${ADMITTED_RECTOR_AGENT.version}` }); expect(result.interpretation.sourceRefs).toContain(`${ADMITTED_RECTOR_AGENT.identity}@${ADMITTED_RECTOR_AGENT.version}`); expect(result.interpretation.payload.determinations).toHaveLength(1); expect(result.result).toMatchObject({ artifactType: "CastellanTurnDisposition", payload: { action: "ACCEPT_AND_ADVANCE" } }); });
  it("leaves relevance and advancement to Castellan", () => { const c = new Cognition(); c.disposition = "UNUSABLE"; const x = turn(c), result = x.rector.evaluateHandoff(x.d, x.h, context); expect(result.result).toMatchObject({ producer: "Castellan", payload: { action: "REQUERY_SAME_QUESTION", operatorFacingMessage: "That is not what I asked." } }); });
  it("rejects invalid handoff before cognition", () => { let calls = 0; const c: RectorCognitivePort = { assessMissionPredicates: () => { calls++; return { determinations: [] }; } }; const x = turn(); expect(() => new RectorCastellanOfficer(c).evaluateHandoff(x.d, { ...x.h, payload: { ...x.h.payload, dossierRef: "other@1" } }, context)).toThrow(); expect(calls).toBe(0); });
  it("rejects cognition that invents a value absent from the exact response", () => { const c: RectorCognitivePort = { assessMissionPredicates: (d, sourceAnswerRef) => { const q = d.presentedQuestions.at(-1)!; return { determinations: [{ questionId: q.questionId, predicate: q.predicate, disposition: "RESOLVED", values: ["Invented mission"], rationale: "Synthetic resolution.", sourceAnswerRef, evidence: [{ exactExcerpt: "Invented mission", derivation: "QUOTED", value: "Invented mission", rationale: "Fabricated excerpt." }] }] }; } }; const x = turn(); expect(() => new RectorCastellanOfficer(c).evaluateHandoff(x.d, x.h, context)).toThrow("exact active Operator answer"); });
  it("completes all eight questions strictly one turn at a time", () => { const isolde = new IsoldeSecretariatOfficer(); const cognition: RectorCognitivePort = { assessMissionPredicates: (d, sourceAnswerRef) => { const q = d.presentedQuestions.at(-1)!, raw = d.answers.at(-1)!.rawAnswer, none = ["constraints", "unknowns", "material_contradictions", "resource_requirements"].includes(q.predicate); return { determinations: [{ questionId: q.questionId, predicate: q.predicate, disposition: none ? "DECLARED_NONE" : "RESOLVED", values: none ? [] : [raw], rationale: none ? "Operator declared none." : "Exact response resolves this turn.", sourceAnswerRef, evidence: [{ exactExcerpt: raw, derivation: "QUOTED", value: none ? undefined : raw, rationale: "Exact Operator wording." }] }] }; } }; const rector = new RectorCastellanOfficer(cognition); let dossier = isolde.openMission("operator@1", "Build mission", "eight-turns", context); for (let index = 0; index < 8; index++) { const result = rector.initiateInquiry(dossier, context); expect(result.artifactType).toBe("CastellanInquiry"); const inquiry = result as GovernedArtifactEnvelope<CastellanInquiry>; const presented = isolde.presentQuestion(dossier, inquiry, context).dossier; const raw = ["constraints", "unknowns", "material_contradictions", "resource_requirements"].includes(inquiry.payload.question.predicate) ? "None" : "Response " + index; const response = isolde.recordResponse(presented, raw, context); const evaluated = rector.evaluateHandoff(response.dossier, response.handoff, context); expect(evaluated.result.artifactType).toBe("CastellanTurnDisposition"); const disposition = evaluated.result as GovernedArtifactEnvelope<CastellanTurnDisposition>; dossier = isolde.relayDisposition(response.dossier, disposition, context).dossier; } const candidate = rector.initiateInquiry(dossier, context); expect(candidate).toMatchObject({ artifactType: "MissionSpecificationCandidate", payload: { purpose: "Response 0", state: "CANDIDATE", authorityCreated: false } }); expect(dossier.payload.presentedQuestions).toHaveLength(8); expect(dossier.payload.answers).toHaveLength(8); expect(dossier.payload.acceptedDeterminations).toHaveLength(8); });
});
