import { ArtifactContext, ArtifactEnvelope, GovernedArtifactContext, GovernedArtifactEnvelope, createGovernedArtifact } from "./artifact.js";
import { ADMITTED_CASTELLAN_PROFILE } from "./castellan-doctrine-profile.js";
import { ENACTED_IMPERIUM_LEXICON_V4 } from "./imperium-lexicon-v4.js";
import { ADMITTED_RECTOR } from "./rector-officer-profile.js";
import { ADMITTED_SECRETARIAT_PROFILE } from "./secretariat-doctrine-profile.js";
import { LexiconAuthority, TerminologyConformanceGate } from "./senate-lexicon.js";
import { AcceptedMissionDetermination, CastellanInquiry, CastellanTurnDisposition, DeterminationEvidence, MissionDossier, MissionFormationPredicate, SecretariatDossierHandoff } from "./secretariat-mission-dossier.js";
import { assertArtifactEnvelope } from "./schema.js";

export type PredicateDisposition = "RESOLVED" | "DECLARED_NONE" | "AMBIGUOUS" | "CONTRADICTORY" | "UNUSABLE";
export interface PredicateDetermination { questionId: string; predicate: MissionFormationPredicate; disposition: PredicateDisposition; values: string[]; rationale: string; sourceAnswerRef: string; evidence: DeterminationEvidence[]; }
export interface CastellanPredicateAssessment { dossierRef: string; handoffRef: string; rectorInterpretationRef: string; determination: PredicateDetermination; }
export interface RectorPredicateInterpretationContract { officerPersonaRef: string; dossierRef: string; handoffRef: string; determinations: PredicateDetermination[]; researchPerformed: false; judgmentRendered: false; authorityCreated: false; }
export interface MissionSpecificationCandidate { dossierRef: string; acceptedDeterminationRefs: string[]; purpose: string; scope: string[]; constraints: string[]; acceptanceCriteria: string[]; requestedOutputs: string[]; suppliedClaims: string[]; assumptions: string[]; unknowns: string[]; materialContradictions: string[]; authorityAssertions: string[]; externalObligationAssertions: string[]; resourceRequirements: string[]; unresolvedPredicates: MissionFormationPredicate[]; state: "CANDIDATE"; authorityCreated: false; }
export type CastellanEvaluation = GovernedArtifactEnvelope<CastellanInquiry> | GovernedArtifactEnvelope<CastellanTurnDisposition> | GovernedArtifactEnvelope<MissionSpecificationCandidate>;

const profileRef = ADMITTED_CASTELLAN_PROFILE.identity + "@" + ADMITTED_CASTELLAN_PROFILE.version; const rectorRef = ADMITTED_RECTOR.identity + "@" + ADMITTED_RECTOR.version; const secretariatProfileRef = ADMITTED_SECRETARIAT_PROFILE.identity + "@" + ADMITTED_SECRETARIAT_PROFILE.version; const doctrineRef = ADMITTED_CASTELLAN_PROFILE.payload.coreDoctrineRef; const lexiconRef = ADMITTED_CASTELLAN_PROFILE.payload.lexiconRef;
const gate = new TerminologyConformanceGate(new LexiconAuthority(ENACTED_IMPERIUM_LEXICON_V4.lexicon, lexiconRef));
const prompts: Record<MissionFormationPredicate, [string, string]> = {
  purpose: ["What precise outcome should this mission accomplish?", "Castellan must establish the Operator's intended purpose."], scope: ["What is explicitly in scope and out of scope?", "Mission scope requires explicit boundaries."], constraints: ["What constraints apply? If none, state that explicitly.", "Constraints require an explicit declaration."], acceptance_criteria: ["What observable conditions would count as success?", "Success requires testable acceptance criteria."], requested_outputs: ["What exact outputs should the mission produce?", "Requested outputs require exact definition."], unknowns: ["What material facts remain unknown? If none, state that explicitly.", "Material unknowns must be exposed or cleared."], material_contradictions: ["What contradictions or incompatible requirements remain? If none, state that explicitly.", "Material contradictions must be exposed or cleared."], resource_requirements: ["What people, capabilities, tools, data, access, time, or budget might the mission require? If none, state that explicitly.", "Resource requirements may not be silently invented or omitted."],
};
const order = Object.keys(prompts) as MissionFormationPredicate[]; const noneAllowed = new Set<MigrationPredicate>(["constraints", "unknowns", "material_contradictions", "resource_requirements"]); const mustClear = new Set<MigrationPredicate>(["unknowns", "material_contradictions"]);
type MigrationPredicate = MissionFormationPredicate;

export class CastellanOperatingLayer {
  recordAssessment(dossier: GovernedArtifactEnvelope<MissionDossier>, handoff: GovernedArtifactEnvelope<SecretariatDossierHandoff>, interpretation: GovernedArtifactEnvelope<RectorPredicateInterpretationContract>, context: ArtifactContext = {}): GovernedArtifactEnvelope<CastellanPredicateAssessment> {
    assertCastellanHandoffReceipt(dossier, handoff); assertRectorInterpretation(dossier, handoff, interpretation); validateDetermination(dossier, interpretation.payload.determinations);
    const governance = governed([["LEX-060", "cognitive_process"], ["LEX-063", "mission_formation"], ["LEX-012", "castellan"]]); gate.assertGovernance(governance);
    return createGovernedArtifact("CastellanPredicateAssessment", "CastellanOperatingLayer", dossier.correlationId, { dossierRef: ref(dossier), handoffRef: ref(handoff), rectorInterpretationRef: ref(interpretation), determination: cleanDetermination(interpretation.payload.determinations[0]) }, governance, [ref(dossier), ref(handoff), ref(interpretation), rectorRef, profileRef], context);
  }
}

export class CastellanMissionFormation {
  evaluateGapDriven(dossier: GovernedArtifactEnvelope<MissionDossier>, context: ArtifactContext = {}): GovernedArtifactEnvelope<MissionSpecificationCandidate> {
    assertDossier(dossier);
    if (dossier.payload.state !== "AWAITING_CASTELLAN_INQUIRY" || dossier.payload.presentedQuestions.length || dossier.payload.answers.length) throw new Error("gap-driven formation requires untouched authenticated Operator intent");
    return gapDrivenCandidate(dossier, context);
  }
  evaluate(dossier: GovernedArtifactEnvelope<MissionDossier>, handoff?: GovernedArtifactEnvelope<SecretariatDossierHandoff>, assessment?: GovernedArtifactEnvelope<CastellanPredicateAssessment>, context: ArtifactContext = {}): CastellanEvaluation {
    assertDossier(dossier);
    if (dossier.payload.state === "AWAITING_CASTELLAN_INQUIRY") { const next = order.find((p) => !dossier.payload.acceptedDeterminations.some((d) => d.predicate === p)); return next ? inquire(dossier, next, context) : candidate(dossier, context); }
    assertHandoff(dossier, handoff); assertAssessment(dossier, handoff!, assessment); const d = assessment!.payload.determination; const acceptable = (d.disposition === "RESOLVED" && !mustClear.has(d.predicate)) || (d.disposition === "DECLARED_NONE" && noneAllowed.has(d.predicate));
    const action = acceptable ? "ACCEPT_AND_ADVANCE" : d.disposition === "AMBIGUOUS" ? "REQUEST_EXPLANATION" : d.disposition === "UNUSABLE" ? "REQUERY_SAME_QUESTION" : "REQUERY_SAME_QUESTION";
    const message = acceptable ? "Thank you." : action === "REQUEST_EXPLANATION" ? prompts[d.predicate][1] : "That is not what I asked.";
    const acceptedDetermination: AcceptedMissionDetermination | undefined = acceptable ? { questionId: d.questionId, predicate: d.predicate, disposition: d.disposition as "RESOLVED" | "DECLARED_NONE", values: [...d.values], rationale: d.rationale, sourceAnswerRef: d.sourceAnswerRef, evidence: structuredClone(d.evidence), assessmentRef: ref(assessment!) } : undefined;
    const governance = governed([["LEX-012", "castellan"], ["LEX-063", "mission_formation"], ["LEX-047", "clarification"]]); gate.assertGovernance(governance);
    return createGovernedArtifact("CastellanTurnDisposition", "Castellan", dossier.correlationId, { dossierRef: ref(dossier), questionId: d.questionId, action, operatorFacingMessage: message, acceptedDetermination, authorityCreated: false }, governance, [ref(dossier), ref(handoff!), ref(assessment!), profileRef], context);
  }
}

function inquire(dossier: GovernedArtifactEnvelope<MissionDossier>, predicate: MissionFormationPredicate, context: ArtifactContext): GovernedArtifactEnvelope<CastellanInquiry> { const requery = dossier.payload.lastTurnAction === "REQUERY_SAME_QUESTION"; const wording = requery ? "That is not what I asked. " + prompts[predicate][0] : prompts[predicate][0]; const governance = governed([["LEX-046", "inquiry"], ["LEX-012", "castellan"], ["LEX-063", "mission_formation"]]); gate.assertGovernance(governance); return createGovernedArtifact("CastellanInquiry", "Castellan", dossier.correlationId, { dossierRef: ref(dossier), question: { questionId: `mission_formation.${predicate}.${dossier.version}`, predicate, exactQuestion: wording, rationale: prompts[predicate][1], answerRequired: true } }, governance, [ref(dossier), profileRef], context); }
function candidate(dossier: GovernedArtifactEnvelope<MissionDossier>, context: ArtifactContext): GovernedArtifactEnvelope<MissionSpecificationCandidate> { const by = new Map(dossier.payload.acceptedDeterminations.map((d) => [d.predicate, d])); const values = (p: MissionFormationPredicate) => by.get(p)?.disposition === "DECLARED_NONE" ? [] : by.get(p)!.values; const governance = governed([["LEX-062", "mission_specification"], ["LEX-083", "candidate"], ["LEX-012", "castellan"]]); gate.assertGovernance(governance); return createGovernedArtifact("MissionSpecificationCandidate", "Castellan", dossier.correlationId, { dossierRef: ref(dossier), acceptedDeterminationRefs: dossier.payload.acceptedDeterminations.map((d) => d.assessmentRef), purpose: values("purpose")[0], scope: values("scope"), constraints: values("constraints"), acceptanceCriteria: values("acceptance_criteria"), requestedOutputs: values("requested_outputs"), suppliedClaims: [...dossier.payload.suppliedClaims], assumptions: [...dossier.payload.assumptions], unknowns: values("unknowns"), materialContradictions: values("material_contradictions"), authorityAssertions: [...dossier.payload.authorityAssertions], externalObligationAssertions: [...dossier.payload.externalObligationAssertions], resourceRequirements: values("resource_requirements"), unresolvedPredicates: [], state: "CANDIDATE", authorityCreated: false }, governance, [ref(dossier), ...dossier.payload.acceptedDeterminations.map((d) => d.assessmentRef), profileRef], context); }
function gapDrivenCandidate(dossier: GovernedArtifactEnvelope<MissionDossier>, context: ArtifactContext): GovernedArtifactEnvelope<MissionSpecificationCandidate> {
  const unresolvedPredicates: MissionFormationPredicate[] = ["scope", "constraints", "acceptance_criteria", "unknowns", "material_contradictions", "resource_requirements"];
  const governance = governed([["LEX-062", "mission_specification"], ["LEX-083", "candidate"], ["LEX-012", "castellan"]]); gate.assertGovernance(governance);
  return createGovernedArtifact("MissionSpecificationCandidate", "Castellan", dossier.correlationId, { dossierRef: ref(dossier), acceptedDeterminationRefs: [], purpose: dossier.payload.rawIntent, scope: [], constraints: [], acceptanceCriteria: [], requestedOutputs: [dossier.payload.rawIntent], suppliedClaims: [...dossier.payload.suppliedClaims], assumptions: [...dossier.payload.assumptions], unknowns: [], materialContradictions: [], authorityAssertions: [...dossier.payload.authorityAssertions], externalObligationAssertions: [...dossier.payload.externalObligationAssertions], resourceRequirements: [], unresolvedPredicates, state: "CANDIDATE", authorityCreated: false }, governance, [ref(dossier), profileRef], context);
}
function validateDetermination(dossier: GovernedArtifactEnvelope<MissionDossier>, values: PredicateDetermination[]): void {
  if (values.length !== 1) throw new Error("Rector must determine exactly one active question per turn");
  const d = values[0], q = dossier.payload.presentedQuestions.at(-1), a = dossier.payload.answers.at(-1), answerRef = ref(dossier) + "#answer:" + q?.questionId;
  if (!q || !a || d.questionId !== q.questionId || d.predicate !== q.predicate || a.questionId !== q.questionId || d.sourceAnswerRef !== answerRef) throw new Error("determination requires the exact active answered question and answer reference");
  if (!d.rationale.trim() || !d.evidence.length || (d.disposition === "RESOLVED" && !d.values.some((v) => v.trim())) || (d.disposition === "DECLARED_NONE" && d.values.length)) throw new Error("determination disposition, values, evidence, and rationale are inconsistent");
  for (const evidence of d.evidence) {
    if (!evidence.exactExcerpt.trim() || !a.rawAnswer.includes(evidence.exactExcerpt) || !evidence.rationale.trim()) throw new Error("determination evidence must quote the exact active Operator answer");
    if (evidence.derivation === "QUOTED" && evidence.value !== undefined && evidence.value !== evidence.exactExcerpt) throw new Error("quoted determination value must equal its exact excerpt");
  }
  for (const value of d.values.map((v) => v.trim()).filter(Boolean)) if (!d.evidence.some((e) => e.value === value)) throw new Error("every determination value requires exact answer evidence");
  if (d.disposition === "RESOLVED" && d.evidence.some((e) => e.value !== undefined && e.derivation !== "QUOTED")) throw new Error("resolved determination values must remain exact Operator quotations");
  if (d.disposition === "DECLARED_NONE" && d.evidence.some((e) => e.value !== undefined)) throw new Error("declared-none evidence may not create a value");
}
function assertDossier(d: GovernedArtifactEnvelope<MissionDossier>): void { assertArtifactEnvelope(d); if (d.artifactType !== "MissionDossier" || d.producer !== "Secretariat" || d.status !== "CURRENT" || d.payload.doctrineRef !== doctrineRef || d.payload.lexiconRef !== lexiconRef || d.payload.officeProfileRef !== secretariatProfileRef || d.governance.coreDoctrineRef !== doctrineRef || d.governance.lexiconRef !== lexiconRef || d.governance.officeProfileRef !== secretariatProfileRef) throw new Error("exact current governed Secretariat Mission Dossier is required"); gate.assertGovernance(d.governance); validateAcceptedHistory(d); }
function validateAcceptedHistory(d: GovernedArtifactEnvelope<MissionDossier>): void {
  const predicates = new Set<MissionFormationPredicate>();
  for (const accepted of d.payload.acceptedDeterminations) {
    const answer = d.payload.answers.find((a) => a.questionId === accepted.questionId);
    if (predicates.has(accepted.predicate) || !answer || !accepted.sourceAnswerRef.endsWith("#answer:" + accepted.questionId) || !accepted.assessmentRef.trim() || !accepted.evidence.length) throw new Error("accepted determination history requires unique exact answer and assessment lineage");
    predicates.add(accepted.predicate);
    for (const value of accepted.values) if (!accepted.evidence.some((e) => e.derivation === "QUOTED" && e.value === value && e.exactExcerpt === value && answer.rawAnswer.includes(e.exactExcerpt))) throw new Error("accepted determination history contains an unsupported value");
    if (accepted.disposition === "DECLARED_NONE" && (accepted.values.length || accepted.evidence.some((e) => !e.exactExcerpt.trim() || !answer.rawAnswer.includes(e.exactExcerpt) || e.value !== undefined))) throw new Error("accepted declared-none history requires exact valueless answer evidence");
  }
}
function assertHandoff(d: GovernedArtifactEnvelope<MissionDossier>, h?: GovernedArtifactEnvelope<SecretariatDossierHandoff>): void { if (!h) throw new Error("exact Secretariat handoff is required"); assertArtifactEnvelope(h); if (d.payload.state !== "READY_FOR_CASTELLAN_EVALUATION" || h.artifactType !== "SecretariatDossierHandoff" || h.producer !== "Secretariat" || h.status !== "CURRENT" || h.payload.dossierRef !== ref(d) || h.payload.recipient !== "Castellan" || h.payload.purpose !== "MISSION_EVALUATION" || h.payload.authorityCreated !== false || h.correlationId !== d.correlationId || h.governance.coreDoctrineRef !== doctrineRef || h.governance.lexiconRef !== lexiconRef || h.governance.officeProfileRef !== secretariatProfileRef || !h.sourceRefs.includes(ref(d)) || !h.sourceRefs.includes(secretariatProfileRef)) throw new Error("exact matching governed Secretariat handoff is required"); gate.assertGovernance(h.governance); }
function assertAssessment(d: GovernedArtifactEnvelope<MissionDossier>, h: GovernedArtifactEnvelope<SecretariatDossierHandoff>, a?: GovernedArtifactEnvelope<CastellanPredicateAssessment>): void { if (!a) throw new Error("exact Castellan predicate assessment is required"); assertArtifactEnvelope(a); if (a.artifactType !== "CastellanPredicateAssessment" || a.producer !== "CastellanOperatingLayer" || a.status !== "CURRENT" || a.correlationId !== d.correlationId || a.payload.dossierRef !== ref(d) || a.payload.handoffRef !== ref(h) || a.governance.coreDoctrineRef !== doctrineRef || a.governance.lexiconRef !== lexiconRef || a.governance.officeProfileRef !== profileRef || !a.sourceRefs.includes(ref(d)) || !a.sourceRefs.includes(ref(h)) || !a.sourceRefs.includes(a.payload.rectorInterpretationRef) || !a.sourceRefs.includes(rectorRef) || !a.sourceRefs.includes(profileRef)) throw new Error("exact matching governed Castellan predicate assessment is required"); gate.assertGovernance(a.governance); validateDetermination(d, [a.payload.determination]); }
function assertRectorInterpretation(d: GovernedArtifactEnvelope<MissionDossier>, h: GovernedArtifactEnvelope<SecretariatDossierHandoff>, i: GovernedArtifactEnvelope<RectorPredicateInterpretationContract>): void { assertArtifactEnvelope(i); if (i.artifactType !== "RectorPredicateInterpretation" || i.producer !== "Rector" || i.status !== "CURRENT" || i.correlationId !== d.correlationId || i.payload.officerPersonaRef !== rectorRef || i.payload.dossierRef !== ref(d) || i.payload.handoffRef !== ref(h) || i.payload.researchPerformed || i.payload.judgmentRendered || i.payload.authorityCreated || i.governance.coreDoctrineRef !== doctrineRef || i.governance.lexiconRef !== lexiconRef || i.governance.officeProfileRef !== profileRef || !i.sourceRefs.includes(rectorRef) || !i.sourceRefs.includes(profileRef) || !i.sourceRefs.includes(ref(d)) || !i.sourceRefs.includes(ref(h))) throw new Error("exact matching governed Rector predicate interpretation is required"); gate.assertGovernance(i.governance); }
export function assertCastellanHandoffReceipt(d: GovernedArtifactEnvelope<MissionDossier>, h: GovernedArtifactEnvelope<SecretariatDossierHandoff>): void { assertDossier(d); assertHandoff(d, h); }
function cleanDetermination(d: PredicateDetermination): PredicateDetermination { return { ...d, values: d.values.map((x) => x.trim()).filter(Boolean), rationale: d.rationale.trim(), evidence: d.evidence.map((e) => ({ ...e, exactExcerpt: e.exactExcerpt.trim(), value: e.value?.trim(), rationale: e.rationale.trim() })) }; }
function governed(uses: Array<[string, string]>): GovernedArtifactContext { return { coreDoctrineRef: doctrineRef, lexiconRef, officeProfileRef: profileRef, vocabularyUses: uses.map(([termId, value]) => ({ termId, value, lexiconRef })) }; }
function ref(v: { identity: string; version: number }): string { return v.identity + "@" + v.version; }
