import { ArtifactContext, ArtifactEnvelope, GovernedArtifactContext, GovernedArtifactEnvelope, createGovernedArtifact } from "./artifact.js";
import { ADMITTED_CASTELLAN_PROFILE } from "./castellan-doctrine-profile.js";
import { ENACTED_IMPERIUM_LEXICON_V4 } from "./imperium-lexicon-v4.js";
import { ADMITTED_RECTOR } from "./rector-officer-profile.js";
import { ADMITTED_SECRETARIAT_PROFILE } from "./secretariat-doctrine-profile.js";
import { LexiconAuthority, TerminologyConformanceGate } from "./senate-lexicon.js";
import { AcceptedMissionDetermination, CastellanInquiry, CastellanTurnDisposition, MissionDossier, MissionFormationPredicate, SecretariatDossierHandoff } from "./secretariat-mission-dossier.js";
import { assertArtifactEnvelope } from "./schema.js";

export type PredicateDisposition = "RESOLVED" | "DECLARED_NONE" | "AMBIGUOUS" | "CONTRADICTORY" | "UNUSABLE";
export interface PredicateDetermination { questionId: string; predicate: MissionFormationPredicate; disposition: PredicateDisposition; values: string[]; rationale: string; }
export interface CastellanPredicateAssessment { dossierRef: string; handoffRef: string; rectorInterpretationRef: string; determination: PredicateDetermination; }
export interface RectorPredicateInterpretationContract { officerPersonaRef: string; dossierRef: string; handoffRef: string; determinations: PredicateDetermination[]; researchPerformed: false; judgmentRendered: false; authorityCreated: false; }
export interface MissionSpecificationCandidate { dossierRef: string; acceptedDeterminationRefs: string[]; purpose: string; scope: string[]; constraints: string[]; acceptanceCriteria: string[]; requestedOutputs: string[]; suppliedClaims: string[]; assumptions: string[]; unknowns: string[]; materialContradictions: string[]; authorityAssertions: string[]; externalObligationAssertions: string[]; resourceRequirements: string[]; state: "CANDIDATE"; authorityCreated: false; }
export type CastellanEvaluation = GovernedArtifactEnvelope<CastellanInquiry> | GovernedArtifactEnvelope<CastellanTurnDisposition> | GovernedArtifactEnvelope<MissionSpecificationCandidate>;

const profileRef = ADMITTED_CASTELLAN_PROFILE.identity + "@" + ADMITTED_CASTELLAN_PROFILE.version; const rectorRef = ADMITTED_RECTOR.identity + "@" + ADMITTED_RECTOR.version; const secretariatProfileRef = ADMITTED_SECRETARIAT_PROFILE.identity + "@" + ADMITTED_SECRETARIAT_PROFILE.version; const doctrineRef = ADMITTED_CASTELLAN_PROFILE.payload.coreDoctrineRef; const lexiconRef = ADMITTED_CASTELLAN_PROFILE.payload.lexiconRef;
const gate = new TerminologyConformanceGate(new LexiconAuthority(ENACTED_IMPERIUM_LEXICON_V4.lexicon, lexiconRef));
const prompts: Record<MissionFormationPredicate, [string, string]> = {
  purpose: ["What precise outcome should this mission accomplish?", "Castellan must establish the Operator's intended purpose."], scope: ["What is explicitly in scope and out of scope?", "Mission scope requires explicit boundaries."], constraints: ["What constraints apply? If none, state that explicitly.", "Constraints require an explicit declaration."], acceptance_criteria: ["What observable conditions would count as success?", "Success requires testable acceptance criteria."], requested_outputs: ["What exact outputs should the mission produce?", "Requested outputs require exact definition."], unknowns: ["What material facts remain unknown? If none, state that explicitly.", "Material unknowns must be exposed or cleared."], material_contradictions: ["What contradictions or incompatible requirements remain? If none, state that explicitly.", "Material contradictions must be exposed or cleared."], resource_requirements: ["What people, capabilities, tools, data, access, time, or budget might the mission require? If none, state that explicitly.", "Resource requirements may not be silently invented or omitted."],
};
const order = Object.keys(prompts) as MissionFormationPredicate[]; const noneAllowed = new Set<MigrationPredicate>(["constraints", "unknowns", "material_contradictions", "resource_requirements"]); const mustClear = new Set<MigrationPredicate>(["unknowns", "material_contradictions"]);
type MigrationPredicate = MissionFormationPredicate;

export class CastellanOperatingLayer {
  recordAssessment(dossier: GovernedArtifactEnvelope<MissionDossier>, handoff: GovernedArtifactEnvelope<SecretariatDossierHandoff>, interpretation: GovernedArtifactEnvelope<RectorPredicateInterpretationContract>, context: ArtifactContext = {}): GovernedArtifactEnvelope<CastellanPredicateAssessment> {
    assertCastellanHandoffReceipt(dossier, handoff); assertRectorInterpretation(dossier, handoff, interpretation); validateDetermination(dossier, interpretation.payload.determinations);
    const governance = governed([["LEX-060", "cognitive_process"], ["LEX-063", "mission_formation"], ["LEX-012", "castellan"]]); gate.assertGovernance(governance);
    return createGovernedArtifact("CastellanPredicateAssessment", "CastellanOperatingLayer", dossier.correlationId, { dossierRef: ref(dossier), handoffRef: ref(handoff), rectorInterpretationRef: ref(interpretation), determination: cleanDetermination(interpretation.payload.determinations[0]) }, governance, [ref(dossier), ref(handoff), ref(interpretation), rectorRef, profileRef], context);
  }
}

export class CastellanMissionFormation {
  evaluate(dossier: GovernedArtifactEnvelope<MissionDossier>, handoff?: GovernedArtifactEnvelope<SecretariatDossierHandoff>, assessment?: GovernedArtifactEnvelope<CastellanPredicateAssessment>, context: ArtifactContext = {}): CastellanEvaluation {
    assertDossier(dossier);
    if (dossier.payload.state === "AWAITING_CASTELLAN_INQUIRY") { const next = order.find((p) => !dossier.payload.acceptedDeterminations.some((d) => d.predicate === p)); return next ? inquire(dossier, next, context) : candidate(dossier, context); }
    assertHandoff(dossier, handoff); assertAssessment(dossier, handoff!, assessment); const d = assessment!.payload.determination; const acceptable = (d.disposition === "RESOLVED" && !mustClear.has(d.predicate)) || (d.disposition === "DECLARED_NONE" && noneAllowed.has(d.predicate));
    const action = acceptable ? "ACCEPT_AND_ADVANCE" : d.disposition === "AMBIGUOUS" ? "REQUEST_EXPLANATION" : d.disposition === "UNUSABLE" ? "REQUERY_SAME_QUESTION" : "REQUERY_SAME_QUESTION";
    const message = acceptable ? "Thank you." : action === "REQUEST_EXPLANATION" ? prompts[d.predicate][1] : "That is not what I asked.";
    const acceptedDetermination: AcceptedMissionDetermination | undefined = acceptable ? { questionId: d.questionId, predicate: d.predicate, disposition: d.disposition as "RESOLVED" | "DECLARED_NONE", values: [...d.values], rationale: d.rationale, assessmentRef: ref(assessment!) } : undefined;
    const governance = governed([["LEX-012", "castellan"], ["LEX-063", "mission_formation"], ["LEX-047", "clarification"]]); gate.assertGovernance(governance);
    return createGovernedArtifact("CastellanTurnDisposition", "Castellan", dossier.correlationId, { dossierRef: ref(dossier), questionId: d.questionId, action, operatorFacingMessage: message, acceptedDetermination, authorityCreated: false }, governance, [ref(dossier), ref(handoff!), ref(assessment!), profileRef], context);
  }
}

function inquire(dossier: GovernedArtifactEnvelope<MissionDossier>, predicate: MissionFormationPredicate, context: ArtifactContext): GovernedArtifactEnvelope<CastellanInquiry> { const requery = dossier.payload.lastTurnAction === "REQUERY_SAME_QUESTION"; const wording = requery ? "That is not what I asked. " + prompts[predicate][0] : prompts[predicate][0]; const governance = governed([["LEX-046", "inquiry"], ["LEX-012", "castellan"], ["LEX-063", "mission_formation"]]); gate.assertGovernance(governance); return createGovernedArtifact("CastellanInquiry", "Castellan", dossier.correlationId, { dossierRef: ref(dossier), question: { questionId: `mission_formation.${predicate}.${dossier.version}`, predicate, exactQuestion: wording, rationale: prompts[predicate][1], answerRequired: true } }, governance, [ref(dossier), profileRef], context); }
function candidate(dossier: GovernedArtifactEnvelope<MissionDossier>, context: ArtifactContext): GovernedArtifactEnvelope<MissionSpecificationCandidate> { const by = new Map(dossier.payload.acceptedDeterminations.map((d) => [d.predicate, d])); const values = (p: MissionFormationPredicate) => by.get(p)?.disposition === "DECLARED_NONE" ? [] : by.get(p)!.values; const governance = governed([["LEX-062", "mission_specification"], ["LEX-083", "candidate"], ["LEX-012", "castellan"]]); gate.assertGovernance(governance); return createGovernedArtifact("MissionSpecificationCandidate", "Castellan", dossier.correlationId, { dossierRef: ref(dossier), acceptedDeterminationRefs: dossier.payload.acceptedDeterminations.map((d) => d.assessmentRef), purpose: values("purpose")[0], scope: values("scope"), constraints: values("constraints"), acceptanceCriteria: values("acceptance_criteria"), requestedOutputs: values("requested_outputs"), suppliedClaims: [...dossier.payload.suppliedClaims], assumptions: [...dossier.payload.assumptions], unknowns: values("unknowns"), materialContradictions: values("material_contradictions"), authorityAssertions: [...dossier.payload.authorityAssertions], externalObligationAssertions: [...dossier.payload.externalObligationAssertions], resourceRequirements: values("resource_requirements"), state: "CANDIDATE", authorityCreated: false }, governance, [ref(dossier), ...dossier.payload.acceptedDeterminations.map((d) => d.assessmentRef), profileRef], context); }
function validateDetermination(dossier: GovernedArtifactEnvelope<MissionDossier>, values: PredicateDetermination[]): void { if (values.length !== 1) throw new Error("Rector must determine exactly one active question per turn"); const d = values[0], q = dossier.payload.presentedQuestions.at(-1), a = dossier.payload.answers.at(-1); if (!q || !a || d.questionId !== q.questionId || d.predicate !== q.predicate || a.questionId !== q.questionId) throw new Error("determination requires the exact active answered question"); if (!d.rationale.trim() || (d.disposition === "RESOLVED" && !d.values.some((v) => v.trim())) || (d.disposition === "DECLARED_NONE" && d.values.length)) throw new Error("determination disposition, values, and rationale are inconsistent"); }
function assertDossier(d: GovernedArtifactEnvelope<MissionDossier>): void { assertArtifactEnvelope(d); if (d.artifactType !== "MissionDossier" || d.producer !== "Secretariat" || d.status !== "CURRENT" || d.payload.officeProfileRef !== secretariatProfileRef || d.governance.officeProfileRef !== secretariatProfileRef) throw new Error("exact current Secretariat Mission Dossier is required"); gate.assertGovernance(d.governance); }
function assertHandoff(d: GovernedArtifactEnvelope<MissionDossier>, h?: GovernedArtifactEnvelope<SecretariatDossierHandoff>): void { if (!h) throw new Error("exact Secretariat handoff is required"); assertArtifactEnvelope(h); if (d.payload.state !== "READY_FOR_CASTELLAN_EVALUATION" || h.artifactType !== "SecretariatDossierHandoff" || h.producer !== "Secretariat" || h.status !== "CURRENT" || h.payload.dossierRef !== ref(d) || h.correlationId !== d.correlationId) throw new Error("exact matching Secretariat handoff is required"); }
function assertAssessment(d: GovernedArtifactEnvelope<MissionDossier>, h: GovernedArtifactEnvelope<SecretariatDossierHandoff>, a?: GovernedArtifactEnvelope<CastellanPredicateAssessment>): void { if (!a) throw new Error("exact Castellan predicate assessment is required"); assertArtifactEnvelope(a); if (a.artifactType !== "CastellanPredicateAssessment" || a.producer !== "CastellanOperatingLayer" || a.payload.dossierRef !== ref(d) || a.payload.handoffRef !== ref(h) || !a.sourceRefs.includes(a.payload.rectorInterpretationRef) || !a.sourceRefs.includes(rectorRef)) throw new Error("exact matching Castellan predicate assessment is required"); validateDetermination(d, [a.payload.determination]); }
function assertRectorInterpretation(d: GovernedArtifactEnvelope<MissionDossier>, h: GovernedArtifactEnvelope<SecretariatDossierHandoff>, i: GovernedArtifactEnvelope<RectorPredicateInterpretationContract>): void { assertArtifactEnvelope(i); if (i.artifactType !== "RectorPredicateInterpretation" || i.producer !== "Rector" || i.status !== "CURRENT" || i.payload.officerPersonaRef !== rectorRef || i.payload.dossierRef !== ref(d) || i.payload.handoffRef !== ref(h) || i.payload.researchPerformed || i.payload.judgmentRendered || i.payload.authorityCreated || !i.sourceRefs.includes(rectorRef)) throw new Error("exact matching Rector predicate interpretation is required"); }
export function assertCastellanHandoffReceipt(d: GovernedArtifactEnvelope<MissionDossier>, h: GovernedArtifactEnvelope<SecretariatDossierHandoff>): void { assertDossier(d); assertHandoff(d, h); }
function cleanDetermination(d: PredicateDetermination): PredicateDetermination { return { ...d, values: d.values.map((x) => x.trim()).filter(Boolean), rationale: d.rationale.trim() }; }
function governed(uses: Array<[string, string]>): GovernedArtifactContext { return { coreDoctrineRef: doctrineRef, lexiconRef, officeProfileRef: profileRef, vocabularyUses: uses.map(([termId, value]) => ({ termId, value, lexiconRef })) }; }
function ref(v: { identity: string; version: number }): string { return v.identity + "@" + v.version; }
