import { createArtifact } from "./artifact.js";
import { ENACTED_CORE_DOCTRINE_V6 } from "./enacted-core-doctrine-v6.js";
import { OfficeDoctrineProfileAdmissionDecision, OfficeDoctrineProfileContract, OfficeDoctrineProfileDraft } from "./office-doctrine-profile.js";
export const COGNITIONIST_PROFILE_DECISION_REF = "DR-090";
export const COGNITIONIST_PROFILE_EFFECTIVE_AT = "2026-08-03T03:00:00.000Z";
const doctrineRef = ENACTED_CORE_DOCTRINE_V6.doctrine.identity + "@6"; const evidenceRef = "tests/cognitionist-office-contract.test.ts";
const contract = new OfficeDoctrineProfileContract(doctrineRef, ENACTED_CORE_DOCTRINE_V6.doctrine.payload.lexiconRef);
const rules: Record<string, [string, string, string]> = {
  "CORE-000": ["Use exact cognitive-medium definitions and lifecycle states.", "Exercise every declared Cognitionist artifact and transition.", "A local cognitive term changes a consequence."],
  "CORE-001": ["Treat model capability, adapter availability, credentials, and connectivity as non-authorizing facts.", "Attempt session planning without each authority prerequisite.", "Capability or access creates authority."],
  "CORE-002": ["Bound every connection and session plan to exact current parent authority.", "Invalidate each parent and inspect refusal.", "A dependent plan widens or outlives authority."],
  "CORE-003": ["Keep provider claims, capability evidence, compatibility findings, uncertainty, and failures distinct.", "Trace each category through admission and planning.", "A provider claim becomes verified capability."],
  "CORE-004": ["Evaluate adapters and models under declared port-relevant methods without preferred-provider weighting.", "Compare equivalent candidate evidence treatment.", "Selection criteria change to favor a provider."],
  "CORE-005": ["Preserve port, Persona, Office, adapter, model, provider, lease-reference, and resource lineage.", "Traverse all output source references.", "Connection lineage is inferred."],
  "CORE-006": ["Require exact immutable versions for every shared cognitive artifact.", "Substitute stale and mismatched versions.", "Names or similarity replace exact versions."],
  "CORE-007": ["Emit complete governed envelopes with uncertainty, limits, and revision conditions.", "Validate every Cognitionist output envelope.", "A required envelope element is absent."],
  "CORE-008": ["Steward cognitive connection artifacts without rewriting Persona, Office, Locksmith, or Runtime artifacts.", "Inspect ownership and mutation behavior.", "Cognitionist silently repairs another steward's artifact."],
  "CORE-009": ["Fail closed only the dependent compatibility, credential request, or session plan.", "Exercise missing capability, lease, authority, and evidence.", "A missing prerequisite becomes approval or global failure."],
  "CORE-010": ["Locally contain defective cognitive inputs without quarantining another steward's artifacts.", "Inject defects and inspect upstream status.", "Cognitionist changes upstream availability."],
  "CORE-011": ["Steward cognition connections only; do not legislate, judge, hold credentials, execute tools, or run Runtime.", "Inspect the public API and negative paths.", "Cognitionist absorbs another institution's power."],
  "CORE-012": ["Produce compatibility and conformance findings, never institutional judgment.", "Search outputs for judgment or compensatory scoring.", "Compatibility is mislabeled as judgment."],
  "CORE-013": ["Keep adapter admission and session planning separate from operational disposition and execution.", "Attempt operation from an admitted adapter.", "Admission triggers a live session."],
  "CORE-014": ["Treat Operator intent only as possible internal cognitive-session demand, not provider permission.", "Trace intent into connection requests.", "Intent authorizes provider use."],
  "CORE-015": ["Record provider terms and external-obligation assertions without deciding applicability.", "Inspect provider records and applicability claims.", "Cognitionist claims legal conformity."],
  "CORE-016": ["Carry independently applicable correction or contest routes without inventing recourse.", "Inspect failure and refusal outputs.", "Universal recourse is manufactured."],
  "CORE-017": ["Require inspectable port compatibility, adapter conformance, failure, usage, and invalidation evidence.", "Run positive and negative evidence matrices.", "Synthetic or absent evidence is called operational proof."],
  "CORE-018": ["Adopt doctrine and Lexicon changes only through assigned-Senator propagation and revalidation.", "Match exact legislative and profile lineage.", "Cognitionist self-legislates or self-admits."],
};
export const COGNITIONIST_PROFILE_DRAFT: OfficeDoctrineProfileDraft = { officeId: "Cognitionist", arena: "SHARED", title: "Cognitionist Office Doctrine Profile v1", purpose: "Steward provider-neutral cognitive ports, models, model adapters, compatibility records, credential requirements, and cognitive-session plans without credential custody or Runtime execution.", issuerAuthorityRef: "DR-073#office-profile-admission", applications: ENACTED_CORE_DOCTRINE_V6.doctrine.payload.provisions.map((p) => { const r = rules[p.provisionId]; return { provisionId: p.provisionId, applicability: "APPLIES" as const, applicationRule: r[0], verificationMethod: r[1], evidenceRequirements: [evidenceRef], invalidationConditions: [r[2]] }; }), domainStandardRefs: ["cognitionist-connection-standard@1"], prohibitedInterpretations: ["A model is an Armory Tool.", "Cognitionist owns or resolves credentials.", "Adapter admission authorizes a cognitive session.", "Model output establishes semantic correctness."], profileRevisionConditions: ["Core Doctrine, Lexicon, or Cognitionist jurisdiction changes.", "Cognitive-port, model-adapter, credential-reference, or session-plan contracts change.", "Pressure testing reveals authority, custody, compatibility, or lineage failure."], terminologyGateEvidenceRefs: [evidenceRef] };
export const COGNITIONIST_PROFILE_CANDIDATE = contract.draft(ENACTED_CORE_DOCTRINE_V6.doctrine, COGNITIONIST_PROFILE_DRAFT, "cognitionist-profile-001", { identityFactory: (p) => p + "-cognitionist", now: () => COGNITIONIST_PROFILE_EFFECTIVE_AT });
export const COGNITIONIST_PROFILE_ADMISSION_DECISION = createArtifact<OfficeDoctrineProfileAdmissionDecision>("OfficeDoctrineProfileAdmissionDecision", "Senator:" + COGNITIONIST_PROFILE_CANDIDATE.payload.assignedSenatorId, COGNITIONIST_PROFILE_CANDIDATE.correlationId, { profileCandidateRef: COGNITIONIST_PROFILE_CANDIDATE.identity + "@1", conformanceEvidenceRefs: [evidenceRef], admissionAuthorityRef: "DR-073#office-profile-admission", authorityFindingRef: "DR-090#authority-effective", disposition: "ADMIT" }, [COGNITIONIST_PROFILE_CANDIDATE.identity + "@1", evidenceRef, "DR-073#office-profile-admission", "DR-090#authority-effective"], { identityFactory: (p) => p + "-cognitionist", now: () => COGNITIONIST_PROFILE_EFFECTIVE_AT });
export const ADMITTED_COGNITIONIST_PROFILE = contract.admitByAssignedSenator(COGNITIONIST_PROFILE_CANDIDATE, COGNITIONIST_PROFILE_ADMISSION_DECISION);
