import { ArtifactContext, ArtifactEnvelope, GovernedArtifactContext, GovernedArtifactEnvelope, createGovernedArtifact } from "./artifact.js";
import { ADMITTED_COGNITIONIST_PROFILE } from "./cognitionist-doctrine-profile.js";
import { ENACTED_IMPERIUM_LEXICON_V4 } from "./imperium-lexicon-v4.js";
import { LexiconAuthority, TerminologyConformanceGate } from "./senate-lexicon.js";
import { assertArtifactEnvelope } from "./schema.js";
export interface CognitivePortSpecification { portId: string; operations: string[]; inputSchemaRefs: string[]; outputSchemaRefs: string[]; failureModes: string[]; evidenceRequirements: string[]; }
export interface ModelAdapterSpecification { cognitivePortRef: string; providerRef: string; modelRef: string; adapterVersion: string; supportedOperations: string[]; structuredOutput: boolean; configurationSchemaRef: string; failureModes: string[]; usageEvidenceFields: string[]; credentialRequirementClass: string; state: "CANDIDATE" | "ADMITTED"; admissionDecisionRef?: string; }
export interface AdapterAdmissionDecision { adapterCandidateRef: string; conformanceEvidenceRefs: string[]; authorityRef: string; disposition: "ADMIT" | "DENY"; }
export interface CognitiveConnectionRequest { officerPersonaRef: string; officeProfileRef: string; cognitivePortRef: string; providerRef: string; modelRef: string; resourceEnvelopeRef: string; authorityRef: string; }
export interface CredentialRequirementRequest { connectionRequestRef: string; adapterRef: string; recipient: "Locksmith"; providerRef: string; authenticationClass: string; permittedOfficerPersonaRef: string; permittedOfficeProfileRef: string; authorityRef: string; secretMaterialIncluded: false; }
export interface CognitiveSessionPlan { connectionRequestRef: string; adapterRef: string; credentialLeaseRef: string; compatibilityEvidenceRefs: string[]; resourceEnvelopeRef: string; runtimeRecipient: "MasterMason"; state: "CANDIDATE"; liveSessionCreated: false; }
const profileRef = ADMITTED_COGNITIONIST_PROFILE.identity + "@2"; const doctrineRef = ADMITTED_COGNITIONIST_PROFILE.payload.coreDoctrineRef; const lexiconRef = ADMITTED_COGNITIONIST_PROFILE.payload.lexiconRef;
const gate = new TerminologyConformanceGate(new LexiconAuthority(ENACTED_IMPERIUM_LEXICON_V4.lexicon, lexiconRef));
export class Cognitionist {
  registerAdapter(port: GovernedArtifactEnvelope<CognitivePortSpecification>, draft: Omit<ModelAdapterSpecification, "cognitivePortRef" | "state">, correlationId: string, context: ArtifactContext = {}) { assertPort(port); assertNoSecretMaterial(draft); if (!draft.providerRef.trim() || !draft.modelRef.trim() || !draft.adapterVersion.trim() || !draft.configurationSchemaRef.trim() || !draft.credentialRequirementClass.trim() || !draft.supportedOperations.length || !draft.failureModes.length || !draft.usageEvidenceFields.length) throw new Error("complete model adapter specification is required"); for (const operation of draft.supportedOperations) if (!port.payload.operations.includes(operation)) throw new Error("adapter declares an operation outside the exact cognitive port"); const governance = governed([["LEX-084", "cognitionist"], ["LEX-085", "cognitive_port"], ["LEX-087", "model_adapter"], ["LEX-088", "model"]]); gate.assertGovernance(governance); return createGovernedArtifact<ModelAdapterSpecification>("ModelAdapterSpecification", "Cognitionist", correlationId, { ...draft, cognitivePortRef: ref(port), state: "CANDIDATE" }, governance, [ref(port), draft.providerRef, draft.modelRef, doctrineRef, lexiconRef, profileRef], context); }
  admitAdapter(candidate: GovernedArtifactEnvelope<ModelAdapterSpecification>, decision: ArtifactEnvelope<AdapterAdmissionDecision>): GovernedArtifactEnvelope<ModelAdapterSpecification> { assertAdapter(candidate, "CANDIDATE"); assertArtifactEnvelope(decision); if (decision.artifactType !== "AdapterAdmissionDecision" || decision.producer !== "Cognitionist" || decision.payload.adapterCandidateRef !== ref(candidate) || decision.payload.disposition !== "ADMIT" || !decision.payload.authorityRef.trim() || !decision.sourceRefs.includes(decision.payload.authorityRef) || !decision.payload.conformanceEvidenceRefs.length || decision.payload.conformanceEvidenceRefs.some((x) => !decision.sourceRefs.includes(x))) throw new Error("exact Cognitionist adapter admission decision and evidence are required"); return { ...candidate, version: candidate.version + 1, supersedes: ref(candidate), payload: { ...candidate.payload, state: "ADMITTED", admissionDecisionRef: ref(decision) }, sourceRefs: unique([...candidate.sourceRefs, ...decision.sourceRefs, ref(decision)]) }; }
  requestCredential(connection: GovernedArtifactEnvelope<CognitiveConnectionRequest>, adapter: GovernedArtifactEnvelope<ModelAdapterSpecification>, context: ArtifactContext = {}) { assertConnection(connection); assertAdapter(adapter, "ADMITTED"); if (adapter.payload.cognitivePortRef !== connection.payload.cognitivePortRef || adapter.payload.providerRef !== connection.payload.providerRef || adapter.payload.modelRef !== connection.payload.modelRef) throw new Error("adapter does not match the exact cognitive connection request"); const governance = governed([["LEX-084", "cognitionist"], ["LEX-067", "credential"], ["LEX-082", "provider"], ["LEX-042", "handoff"]]); gate.assertGovernance(governance); return createGovernedArtifact<CredentialRequirementRequest>("CredentialRequirementRequest", "Cognitionist", connection.correlationId, { connectionRequestRef: ref(connection), adapterRef: ref(adapter), recipient: "Locksmith", providerRef: adapter.payload.providerRef, authenticationClass: adapter.payload.credentialRequirementClass, permittedOfficerPersonaRef: connection.payload.officerPersonaRef, permittedOfficeProfileRef: connection.payload.officeProfileRef, authorityRef: connection.payload.authorityRef, secretMaterialIncluded: false }, governance, [ref(connection), ref(adapter), connection.payload.authorityRef, profileRef], context); }
  planSession(connection: GovernedArtifactEnvelope<CognitiveConnectionRequest>, adapter: GovernedArtifactEnvelope<ModelAdapterSpecification>, credentialLeaseRef: string, compatibilityEvidenceRefs: string[], context: ArtifactContext = {}) { assertConnection(connection); assertAdapter(adapter, "ADMITTED"); if (!credentialLeaseRef.trim() || !compatibilityEvidenceRefs.length || adapter.payload.cognitivePortRef !== connection.payload.cognitivePortRef || adapter.payload.providerRef !== connection.payload.providerRef || adapter.payload.modelRef !== connection.payload.modelRef) throw new Error("exact compatible adapter, credential lease reference, and evidence are required"); const governance = governed([["LEX-084", "cognitionist"], ["LEX-086", "cognitive_medium"], ["LEX-089", "cognitive_session"], ["LEX-020", "runtime"]]); gate.assertGovernance(governance); return createGovernedArtifact<CognitiveSessionPlan>("CognitiveSessionPlan", "Cognitionist", connection.correlationId, { connectionRequestRef: ref(connection), adapterRef: ref(adapter), credentialLeaseRef: credentialLeaseRef.trim(), compatibilityEvidenceRefs: unique(compatibilityEvidenceRefs), resourceEnvelopeRef: connection.payload.resourceEnvelopeRef, runtimeRecipient: "MasterMason", state: "CANDIDATE", liveSessionCreated: false }, governance, [ref(connection), ref(adapter), credentialLeaseRef.trim(), ...compatibilityEvidenceRefs, connection.payload.resourceEnvelopeRef, profileRef], context); }
}
export function createCognitivePort(payload: CognitivePortSpecification, producer: string, correlationId: string, officeProfileRef: string, context: ArtifactContext = {}) { if (!payload.portId.trim() || !payload.operations.length || !payload.inputSchemaRefs.length || !payload.outputSchemaRefs.length || !payload.failureModes.length || !payload.evidenceRequirements.length) throw new Error("complete cognitive port specification is required"); const governance = governed([["LEX-085", "cognitive_port"], ["LEX-060", "cognitive_process"], ["LEX-048", "agent"]], officeProfileRef); gate.assertGovernance(governance); return createGovernedArtifact("CognitivePortSpecification", producer, correlationId, payload, governance, [officeProfileRef, doctrineRef, lexiconRef], context); }
export function createConnectionRequest(port: GovernedArtifactEnvelope<CognitivePortSpecification>, payload: Omit<CognitiveConnectionRequest, "cognitivePortRef">, correlationId: string, context: ArtifactContext = {}) { assertPort(port); assertNoSecretMaterial(payload); for (const value of Object.values(payload)) if (typeof value === "string" && !value.trim()) throw new Error("complete cognitive connection request is required"); const governance = governed([["LEX-084", "cognitionist"], ["LEX-085", "cognitive_port"], ["LEX-088", "model"], ["LEX-082", "provider"]]); gate.assertGovernance(governance); const request = { ...payload, cognitivePortRef: ref(port) }; return createGovernedArtifact("CognitiveConnectionRequest", "Cognitionist", correlationId, request, governance, [ref(port), ...Object.values(payload)], context); }
function assertPort(value: GovernedArtifactEnvelope<CognitivePortSpecification>) { assertArtifactEnvelope(value); if (value.artifactType !== "CognitivePortSpecification" || value.status !== "CURRENT" || value.governance.coreDoctrineRef !== doctrineRef || value.governance.lexiconRef !== lexiconRef) throw new Error("exact current cognitive port is required"); gate.assertGovernance(value.governance); }
function assertAdapter(value: GovernedArtifactEnvelope<ModelAdapterSpecification>, state: ModelAdapterSpecification["state"]) { assertArtifactEnvelope(value); if (value.artifactType !== "ModelAdapterSpecification" || value.producer !== "Cognitionist" || value.status !== "CURRENT" || value.payload.state !== state || value.governance.officeProfileRef !== profileRef) throw new Error(`exact ${state.toLowerCase()} Cognitionist model adapter is required`); gate.assertGovernance(value.governance); }
function assertConnection(value: GovernedArtifactEnvelope<CognitiveConnectionRequest>) { assertArtifactEnvelope(value); assertNoSecretMaterial(value.payload); if (value.artifactType !== "CognitiveConnectionRequest" || value.producer !== "Cognitionist" || value.status !== "CURRENT" || value.governance.officeProfileRef !== profileRef) throw new Error("exact current Cognitionist connection request is required"); gate.assertGovernance(value.governance); }
function assertNoSecretMaterial(value: unknown) { const forbidden = /(^|_)(token|password|secret|api_key|credential_value)($|_)/i; const walk = (item: unknown): void => { if (!item || typeof item !== "object") return; for (const [key, child] of Object.entries(item as Record<string, unknown>)) { if (forbidden.test(key)) throw new Error("Cognitionist artifacts may not contain credential material"); walk(child); } }; walk(value); }
function governed(uses: Array<[string, string]>, consumerProfileRef = profileRef): GovernedArtifactContext { return { coreDoctrineRef: doctrineRef, lexiconRef, officeProfileRef: consumerProfileRef, vocabularyUses: uses.map(([termId, value]) => ({ termId, value, lexiconRef })) }; }
function ref(value: { identity: string; version: number }) { return value.identity + "@" + value.version; } function unique(values: string[]) { return [...new Set(values.map((x) => x.trim()).filter(Boolean))].sort(); }
