import { createArtifact } from "./artifact.js";
import { ENACTED_IMPERIUM_LEXICON_V3, imperiumLexiconV3Bill } from "./imperium-lexicon-v3.js";
import { LexiconCategory, LexiconEntry, LexiconLegislativeAuthority, SenateLexicon } from "./senate-lexicon.js";

export const IMPERIUM_LEXICON_V4_DECISION_REF = "DR-087";
export const IMPERIUM_LEXICON_V4_EFFECTIVE_AT = "2026-08-03T00:00:00.000Z";
const evidenceRef = "tests/cognitionist-office-contract.test.ts";
function entry(termId: string, canonicalTerm: string, canonicalValue: string, definition: string, category: LexiconCategory, relatedTermIds: string[]): LexiconEntry { return { termId, canonicalTerm, canonicalValue, definition, category, permittedUses: [`Use ${canonicalValue} only for a subject satisfying the exact definition and cited current Lexicon.`], prohibitedInterpretations: [`Do not infer authority, credential custody, model suitability, session authorization, or semantic correctness from ${canonicalValue} alone.`], relatedTermIds, examples: [`A governed Cognitionist artifact cites ${termId} and the exact value ${canonicalValue}.`], counterexamples: [`An Office uses ${canonicalValue} as an informal synonym without its required boundary.`], revisionConditions: [`Senate changes ${termId} or a related cognitive-medium boundary.`], state: "ACTIVE" }; }
const additions = [
  entry("LEX-084", "Cognitionist", "cognitionist", "The shared Imperium Office that stewards cognitive-medium, model, adapter, compatibility, and cognitive-session connection artifacts while neither owning credentials nor determining the semantic correctness of an Officer's cognition.", "INSTITUTION", ["LEX-048", "LEX-067", "LEX-082"]),
  entry("LEX-085", "Cognitive Port", "cognitive_port", "A provider-neutral versioned interface declaring the cognitive operations, input/output schemas, failure behavior, and evidence obligations required by an admitted Persona or Office role.", "ARTIFACT", ["LEX-048", "LEX-060", "LEX-086"]),
  entry("LEX-086", "Cognitive Medium", "cognitive_medium", "The admitted model-backed medium through which an Agent performs a Cognitive Process; it supplies cognition capability but creates no Office jurisdiction, authority, truth, credential custody, or external-action permission.", "OPERATIONAL", ["LEX-020", "LEX-048", "LEX-088"]),
  entry("LEX-087", "Model Adapter", "model_adapter", "A versioned provider-specific implementation that translates an exact Cognitive Port to and from one declared Model interface while preserving schemas, configuration, failure, usage, and model-version evidence.", "ARTIFACT", ["LEX-082", "LEX-085", "LEX-088"]),
  entry("LEX-088", "Model", "model", "A declared version or stable provider identifier for a computational system supplying cognitive generation or interpretation capability; capability does not establish suitability, authority, or correctness.", "ARTIFACT", ["LEX-082", "LEX-086", "LEX-087"]),
  entry("LEX-089", "Cognitive Session", "cognitive_session", "A bounded Runtime instance connecting one exact admitted Persona and Cognitive Port to an admitted Model Adapter and Model under exact configuration, resource, credential-lease, and authority references.", "OPERATIONAL", ["LEX-020", "LEX-048", "LEX-067", "LEX-085", "LEX-087"]),
];
export function imperiumLexiconV4Bill() { const prior = imperiumLexiconV3Bill(); return { ...prior, rationale: "Admit the shared Cognitionist and provider-neutral cognitive-medium vocabulary.", senateDecisionRef: IMPERIUM_LEXICON_V4_DECISION_REF, effectiveAt: IMPERIUM_LEXICON_V4_EFFECTIVE_AT, entries: [...prior.entries, ...additions], affectedSurfaces: ["COGNITIONIST", "OFFICER_COGNITIVE_PORTS", "RUNTIME", "LOCKSMITH"], transitionRule: "MANDATORY_REVALIDATION" as const, changes: additions.map((item) => ({ termId: item.termId, kind: "ADDITION" as const, compatibility: "REVALIDATION_REQUIRED" as const, rationale: "Admit a previously undefined cognitive-medium boundary.", affectedSurfaces: ["COGNITIONIST", "OFFICER_COGNITIVE_PORTS", "RUNTIME", "LOCKSMITH"], evidenceRefs: [evidenceRef] })) }; }
export const IMPERIUM_LEXICON_V4_AUTHORITY = createArtifact<LexiconLegislativeAuthority>("LexiconLegislativeAuthority", "Senate", "imperium-lexicon-v1", { decisionRef: IMPERIUM_LEXICON_V4_DECISION_REF, action: "AMEND", currentLexiconRef: ENACTED_IMPERIUM_LEXICON_V3.lexicon.identity + "@3", authorityBasisRef: "DR-069#senate-lexicon-jurisdiction", authorityFindingRef: "DR-087#authority-effective", disposition: "AUTHORIZE" }, ["DR-069#senate-lexicon-jurisdiction", "DR-087#authority-effective"], { identityFactory: (p) => p + "-v4", now: () => IMPERIUM_LEXICON_V4_EFFECTIVE_AT });
export const ENACTED_IMPERIUM_LEXICON_V4 = new SenateLexicon(IMPERIUM_LEXICON_V4_AUTHORITY.identity + "@1").amend(ENACTED_IMPERIUM_LEXICON_V3.lexicon, imperiumLexiconV4Bill(), IMPERIUM_LEXICON_V4_AUTHORITY, { identityFactory: (p) => p + "-core-v4", now: () => IMPERIUM_LEXICON_V4_EFFECTIVE_AT });
