import { ArtifactContext, GovernedArtifactContext, GovernedArtifactEnvelope, createGovernedArtifact } from "./artifact.js";
import { ENACTED_IMPERIUM_LEXICON_V4 } from "./imperium-lexicon-v4.js";
import { ADMITTED_ISOLDE } from "./isolde-officer-profile.js";
import { ADMITTED_ISOLDE_AGENT } from "./isolde-agent-definition.js";
import { ADMITTED_ISOLDE_BASE_PERSONA } from "./isolde-base-persona.js";
import { ResidentAgentContract } from "./resident-agent.js";
import { ADMITTED_SECRETARIAT_PROFILE } from "./secretariat-doctrine-profile.js";
import { LexiconAuthority, TerminologyConformanceGate } from "./senate-lexicon.js";
import { CastellanInquiry, CastellanTurnDisposition, IsoldeDispositionRelay, IsoldeQuestionPresentation, IsoldeResponseReceipt, MissionDossier, SecretariatMissionIntake } from "./secretariat-mission-dossier.js";
import { assertArtifactEnvelope } from "./schema.js";

const officerRef = ADMITTED_ISOLDE.identity + "@" + ADMITTED_ISOLDE.version; const officeProfileRef = ADMITTED_SECRETARIAT_PROFILE.identity + "@" + ADMITTED_SECRETARIAT_PROFILE.version; const doctrineRef = ADMITTED_SECRETARIAT_PROFILE.payload.coreDoctrineRef; const lexiconRef = ADMITTED_SECRETARIAT_PROFILE.payload.lexiconRef;
const gate = new TerminologyConformanceGate(new LexiconAuthority(ENACTED_IMPERIUM_LEXICON_V4.lexicon, lexiconRef));
const agentRef = ADMITTED_ISOLDE_AGENT.identity + "@" + ADMITTED_ISOLDE_AGENT.version;

export class IsoldeSecretariatOfficer {
  private readonly intake = new SecretariatMissionIntake();
  constructor() { if (ADMITTED_ISOLDE.payload.state !== "ADMITTED" || ADMITTED_ISOLDE.payload.officeProfileRef !== officeProfileRef) throw new Error("current admitted Isolde Officer contract is required"); new ResidentAgentContract().assertAssembly(ADMITTED_ISOLDE_AGENT, ADMITTED_ISOLDE_BASE_PERSONA, ADMITTED_SECRETARIAT_PROFILE); }
  openMission(authenticatedOperatorRef: string, rawUtterance: string, correlationId: string, context: ArtifactContext = {}) { return this.intake.open({ authenticatedOperatorRef, rawIntent: rawUtterance, officerPersonaRef: officerRef, residentAgentDefinitionRef: agentRef }, correlationId, context); }
  presentQuestion(dossier: GovernedArtifactEnvelope<MissionDossier>, inquiry: GovernedArtifactEnvelope<CastellanInquiry>, context: ArtifactContext = {}) { assertInputDossier(dossier); assertArtifactEnvelope(inquiry); const q = inquiry.payload.question; const governance = governed([["LEX-049", "officer"], ["LEX-011", "secretariat"], ["LEX-046", "inquiry"]]); gate.assertGovernance(governance); const presentation = createGovernedArtifact<IsoldeQuestionPresentation>("IsoldeQuestionPresentation", "Isolde", dossier.correlationId, { dossierRef: ref(dossier), inquiryRef: ref(inquiry), officerPersonaRef: officerRef, questionId: q.questionId, exactQuestion: q.exactQuestion }, governance, [ref(dossier), ref(inquiry), officerRef], context); return { presentation, dossier: this.intake.presentInquiry(dossier, inquiry, presentation) }; }
  recordResponse(dossier: GovernedArtifactEnvelope<MissionDossier>, rawResponse: string, context: ArtifactContext = {}) { assertInputDossier(dossier); if (dossier.payload.state !== "AWAITING_OPERATOR" || !rawResponse.trim()) throw new Error("one exact nonblank Operator response is required"); const q = dossier.payload.presentedQuestions.at(-1)!; const governance = governed([["LEX-049", "officer"], ["LEX-011", "secretariat"], ["LEX-010", "operator"]]); gate.assertGovernance(governance); const receipt = createGovernedArtifact<IsoldeResponseReceipt>("IsoldeResponseReceipt", "Isolde", dossier.correlationId, { dossierRef: ref(dossier), inquiryRef: dossier.payload.activeInquiryRef!, officerPersonaRef: officerRef, questionId: q.questionId, rawResponse }, governance, [ref(dossier), dossier.payload.activeInquiryRef!, officerRef], context); const answered = this.intake.recordAnswers(dossier, [{ questionId: q.questionId, rawAnswer: rawResponse }], receipt); return { receipt, dossier: answered, handoff: this.intake.prepareCastellanHandoff(answered, context) }; }
  relayDisposition(dossier: GovernedArtifactEnvelope<MissionDossier>, disposition: GovernedArtifactEnvelope<CastellanTurnDisposition>, context: ArtifactContext = {}) { assertInputDossier(dossier); assertArtifactEnvelope(disposition); const governance = governed([["LEX-049", "officer"], ["LEX-011", "secretariat"], ["LEX-042", "handoff"]]); gate.assertGovernance(governance); const relay = createGovernedArtifact<IsoldeDispositionRelay>("IsoldeDispositionRelay", "Isolde", dossier.correlationId, { dossierRef: ref(dossier), dispositionRef: ref(disposition), officerPersonaRef: officerRef, action: disposition.payload.action, exactMessage: disposition.payload.operatorFacingMessage }, governance, [ref(dossier), ref(disposition), officerRef], context); return { relay, dossier: this.intake.recordCastellanDisposition(dossier, disposition, relay) }; }
}

export const ISOLDE_RESIDENT_AGENT_REF = agentRef;

function assertInputDossier(d: GovernedArtifactEnvelope<MissionDossier>): void { assertArtifactEnvelope(d); if (d.artifactType !== "MissionDossier" || d.producer !== "Secretariat" || d.status !== "CURRENT" || d.payload.officerPersonaRef !== officerRef || d.payload.residentAgentDefinitionRef !== agentRef || d.payload.officeProfileRef !== officeProfileRef || d.governance.officeProfileRef !== officeProfileRef) throw new Error("exact current Isolde-opened Mission Dossier is required"); gate.assertGovernance(d.governance); }
function governed(uses: Array<[string, string]>): GovernedArtifactContext { return { coreDoctrineRef: doctrineRef, lexiconRef, officeProfileRef, vocabularyUses: uses.map(([termId, value]) => ({ termId, value, lexiconRef })) }; }
function ref(v: { identity: string; version: number }): string { return v.identity + "@" + v.version; }
